version: 2

sources:
  - name: raw_data
    schema: raw_data
    tables: 
      - name: titles
        columns:
          - name: "show_id"
            tests:
              - not_null
              - unique
          - name: "title"
            tests:
              - not_null
        