version: 2

sources:
  - name: raw_data
    schema: raw_data
    tables: 
      - name: titles
        

models: 
  - name: series
    columns:
      - name: "id"
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - unique

  - name: movies
    columns:
      - name: "id"
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - unique